version: '3'

volumes:
  db:

services:
  autogpt:
    image: dogtititi/autogpt-next-web:latest
    container_name: autogpt
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY} # openai api key
      NEXT_PUBLIC_WEB_SEARCH_ENABLED: ${NEXT_PUBLIC_WEB_SEARCH_ENABLED} # enable web search
      SERP_API_KEY: ${SERP_API_KEY} # serp api key
    ports:
      - 3000:3000
    volumes:
      - db:/app/db
    restart: unless-stopped
